// <auto-generated />
using System;
using GrpcServiceReservations.data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GrpcServiceReservations.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    [Migration("20201130174634_init7")]
    partial class init7
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Shared.model.Car", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<DateTime>("InCirculationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastMaintenace")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("NextMaintenace")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Operational")
                        .HasColumnType("bit");

                    b.Property<string>("PlateNbr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Remarks")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Car");
                });

            modelBuilder.Entity("Shared.model.TimeSlot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<DateTime>("EndSlot")
                        .HasColumnType("datetime2")
                        .HasColumnName("EndSlot");

                    b.Property<DateTime>("StartSlot")
                        .HasColumnType("datetime2")
                        .HasColumnName("StartSlot");

                    b.HasKey("Id");

                    b.HasIndex("CarId");

                    b.ToTable("TimeSlots");
                });

            modelBuilder.Entity("Shared.model.TimeSlot", b =>
                {
                    b.HasOne("Shared.model.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });
#pragma warning restore 612, 618
        }
    }
}
